services:
  user-service:
    build:
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    container_name: user-service-1
    networks:
      - global-network

networks:
  global-network:
    name: global-network
    external: true
    driver: bridge