spring:
  config:
    activate:
      on-profile: "prod"
  application:
    name: "${SPRING_APP_NAME:reservation-service}"

logging:
  pattern:
    console: "${LOG_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}"