spring:
  config:
    activate:
      on-profile: "prod"
  application:
    name: "${SPRING_APP_NAME:user-service}"
  datasource:
    url: "jdbc:${DB_TYPE:postgresql}://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:user_service}"
    username: "${DB_USER:postgres}"
    password: "${DB_PASSWORD:postgres}"
  jpa:
      hibernate:
        ddl-auto: update

logging:
  pattern:
    console: "${LOG_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}"