apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: hah
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      automountServiceAccountToken: false
      containers:
        - name: user-service-container
          image: europe-west3-docker.pkg.dev/gd-gcp-internship-dc/hah-registry/user-service:initial
          env:
            - name: DB_TYPE
              value: "postgresql"
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              value: "user_service"
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
              ephemeral-storage: "256Mi"
            limits:
              memory: "1Gi"