apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: hah
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      automountServiceAccountToken: false
      containers:
        - name: user-service-container
          image: europe-west3-docker.pkg.dev/gd-gcp-internship-dc/hah-registry/user-service:initial
          env:
            - name: DB_TYPE
              value: "postgresql"
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              value: "user_service"
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_HOST
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASSWORD
            - name: BASE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-key-secret
                  key: USER_API_KEY
            - name: AUTH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-key-secret
                  key: AUTH_API_KEY
            - name: EUREKA_SERVICE_URL
              value: http://eureka-naming-server-service:8761/eureka
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
              ephemeral-storage: "256Mi"
            limits:
              memory: "1Gi"