apiVersion: v1
kind: Service
metadata:
  name: user-service-service
  namespace: hah
spec:
  selector:
    app: user-service
  ports:
    - name: gateway
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer